### ISSUE TITLE
Time to refresh in dashboard goes negative

### ISSUE THREAD

**Issue by nmaggioni** [nmaggioni/HubGraph#4]
The time to the next refresh in the dashboard occasionally goes negative after an automatic refresh; as soon as it goes under `-60` a manual refresh fixes it. @giovanniberti

**Comment by giovanniberti** [comment]
The problem lies in the fact that receiving and analyzing the pages takes a few seconds, and only **then** the last update time, from which we derive the next refresh time, is updated. On the other hand, refreshing the page takes a lot less, so the script on the page reads the old `dashboarddata.json` file, with the old `lastUpdate` time (which substracted to the current time is always negative).
